import { UserModel, IUser } from '../database/models/User';
import { WorkspaceModel } from '../database/models/Workspace';
import bcrypt from 'bcrypt';

/**
 * AdminRepository — handles all admin user operations
 * Admins are Users with role='admin'
 */
export class AdminRepository {
  /**
   * Create a new admin user, linked to a workspace.
   * Username and password are auto-generated by the caller.
   */
  public static async createAdmin(params: {
    username: string;
    passwordPlain: string;
    name: string;
    workspaceId?: number;
  }): Promise<IUser | null> {
    try {
      const lower = params.username.toLowerCase();
      const existing = await UserModel.findOne({ username: lower }).lean().exec();
      if (existing) return null;

      const lastUser = await UserModel.findOne().sort({ id: -1 }).exec();
      const nextId = lastUser ? lastUser.id + 1 : 1;

      const passwordHash = await bcrypt.hash(params.passwordPlain, 10);

      const newUser = await UserModel.create({
        id: nextId,
        username: lower,
        passwordHash,
        name: params.name,
        role: 'admin',
        status: 'APPROVED',
        workspaceId: params.workspaceId
      });

      return newUser.toJSON() as IUser;
    } catch (err) {
      console.error('[AdminRepository] createAdmin failed:', err);
      throw err;
    }
  }

  /**
   * Find an admin by their username
   */
  public static async findByUsername(username: string): Promise<IUser | null> {
    const user = await UserModel.findOne({
      username: username.toLowerCase(),
      role: 'admin'
    }).lean().exec();
    return user as IUser | null;
  }

  /**
   * Find an admin by their numeric legacy id
   */
  public static async findById(id: number): Promise<IUser | null> {
    const user = await UserModel.findOne({ id, role: 'admin' }).lean().exec();
    return user as IUser | null;
  }

  /**
   * Find all admin users
   */
  public static async findAll(): Promise<IUser[]> {
    const users = await UserModel.find({ role: 'admin' }).sort({ createdAt: -1 }).lean().exec();
    return users as IUser[];
  }

  /**
   * Delete an admin by numeric id. Also removes workspace association.
   */
  public static async deleteById(id: number): Promise<boolean> {
    const deleted = await UserModel.findOneAndDelete({ id, role: 'admin' });
    if (deleted) {
      await WorkspaceModel.updateOne({ adminId: id }, { $unset: { adminId: 1 } });
      return true;
    }
    return false;
  }

  /**
   * Reset an admin's password
   */
  public static async resetPassword(id: number, newPasswordPlain: string): Promise<boolean> {
    const hash = await bcrypt.hash(newPasswordPlain, 10);
    const result = await UserModel.updateOne({ id, role: 'admin' }, { passwordHash: hash });
    return result.modifiedCount > 0;
  }

  /**
   * Generate a unique admin username based on workspace name
   */
  public static async generateUsername(workspaceName: string): Promise<string> {
    const slug = workspaceName
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '')
      .substring(0, 20);
    const prefix = `admin_${slug}_`;

    const existing = await UserModel.find({
      username: { $regex: new RegExp(`^admin_${slug}_\\d+$`) }
    }).lean().exec();

    let maxSeq = 0;
    for (const u of existing) {
      const parts = u.username.split('_');
      const seq = parseInt(parts[parts.length - 1], 10);
      if (!isNaN(seq) && seq > maxSeq) maxSeq = seq;
    }

    const nextSeq = String(maxSeq + 1).padStart(3, '0');
    return `${prefix}${nextSeq}`;
  }

  /**
   * Generate a random strong password (8+ chars, mixed case + numbers)
   */
  public static generatePassword(length = 10): string {
    const upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
    const lower = 'abcdefghjkmnpqrstuvwxyz';
    const numbers = '23456789';
    const all = upper + lower + numbers;

    let pass = '';
    pass += upper[Math.floor(Math.random() * upper.length)];
    pass += lower[Math.floor(Math.random() * lower.length)];
    pass += numbers[Math.floor(Math.random() * numbers.length)];

    for (let i = 3; i < length; i++) {
      pass += all[Math.floor(Math.random() * all.length)];
    }

    // Shuffle
    return pass.split('').sort(() => 0.5 - Math.random()).join('');
  }
}
